In [11]:
from datasets import load_dataset

ds = load_dataset("ieuniversity/flirty_or_not")

In [12]:
ds

DatasetDict({
    train: Dataset({
        features: ['id', 'label', 'texts'],
        num_rows: 1584
    })
    validation: Dataset({
        features: ['id', 'label', 'texts'],
        num_rows: 212
    })
    test: Dataset({
        features: ['id', 'label', 'texts'],
        num_rows: 318
    })
})

In [13]:
import pandas as pd

splits = {'train': 'data/train-00000-of-00001-4ecde15228eb0f64.parquet', 'validation': 'data/validation-00000-of-00001-ffb59746b9938005.parquet', 'test': 'data/test-00000-of-00001-92a580ceaea25bf5.parquet'}
df = pd.read_parquet("hf://datasets/ieuniversity/flirty_or_not/" + splits["train"])

In [14]:
df

        id  label                                          texts
0     3144      1                     Ah, so I have been told ;)
1     2086      0                                    just honest
2     2826      0              i'm trying to get into med school
3     2993      1  The rhythm of your heart is music to my ears.
4     2016      0                  hi, not bad, how about yours?
...    ...    ...                                            ...
1579  3501      1     My back is arched just thinking about that
1580   442      0                           Definitely a chatmer
1581  2127      0           have you heard of his liquid record?
1582  3439      1                                        Oh baby
1583  2623      1              lol so your name sake is a plant?

[1584 rows x 3 columns]

In [15]:
df["label"].value_counts()

label
1    792
0    792
Name: count, dtype: int64

In [16]:
df_test = pd.read_parquet("hf://datasets/ieuniversity/flirty_or_not/" + splits["test"])

In [17]:
df_test

       id  label                                              texts
0    3194      1                                         oh yeah...
1    3218      1                                   Aaargh... Mhmmmm
2     319      0    Well we matched on Harry lol what’s ur fav song
3    3137      1                                             Hey ;)
4     847      0  Exactly! I think if I were to do college again...
..    ...    ...                                                ...
313  1321      1  Before we go on a date I have to know what the...
314  1372      0                                 I know what u mean
315  3526      1  I was using my wand thinking about you fingeri...
316   147      1    Feeling strong 7 vibes today but 3 is my normal
317  2724      0  and a friend of mine had the weirdest legends ...

[318 rows x 3 columns]

In [18]:
df_val = pd.read_parquet("hf://datasets/ieuniversity/flirty_or_not/" + splits["validation"])

In [19]:
df_val

       id  label                                              texts
0    1538      0                                               sure
1    2011      0                                  congratulations 🐤
2    2991      1        I'd drop everything for you in a heartbeat.
3    1726      0                 i'm a little too old to be adopted
4    2054      0                              alright, how are you?
..    ...    ...                                                ...
207  3240      1                               Me: Well come see me
208  3168      1  Your chest, mmhm... Lickable, Your abs... I li...
209   110      0  Sorry I haven’t checked Tinder in a minute hah...
210  2759      1                                                  😜
211   710      0                       So did u leave the stove on?

[212 rows x 3 columns]

In [20]:
df.drop(columns=["id"], inplace=True)
df_test.drop(columns=["id"], inplace=True)
df_val.drop(columns=["id"], inplace=True)

In [21]:
df.to_csv("train.csv", index=False)
df_test.to_csv("test.csv", index=False)
df_val.to_csv("validation.csv", index=False)