In [15]:
import pandas as pd

In [16]:
df = pd.read_csv("top_rated_movies.csv")

In [17]:
df

,adult,backdrop_path,genre_ids,id,original_language,original_title,overview,popularity,poster_path,release_date,title,video,vote_average,vote_count
0,False,/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg,"[18, 80]",278,en,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,36.9269,/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg,1994-09-23,The Shawshank Redemption,False,8.716,29854
1,False,/tSPT36ZKlP2WVHJLM4cQPLSzv3b.jpg,"[18, 80]",238,en,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",31.9743,/3bhkrj58Vtu7enYsRolD1fZdja1.jpg,1972-03-14,The Godfather,False,8.687,22539
2,False,/kGzFbGhp99zva6oZODW5atUtnqi.jpg,"[18, 80]",240,en,The Godfather Part II,In the continuing saga of the Corleone crime f...,15.4289,/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg,1974-12-20,The Godfather Part II,False,8.571,13645
3,False,/zb6fM1CX41D9rF9hdgclu0peUmy.jpg,"[18, 36, 10752]",424,en,Schindler's List,The true story of how businessman Oskar Schind...,20.0604,/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg,1993-12-15,Schindler's List,False,8.566,17166
4,False,/w4bTBXcqXc2TUyS5Fc4h67uWbPn.jpg,[18],389,en,12 Angry Men,The defense and the prosecution have rested an...,16.9499,/ow3wq89wM8qd5X7hWKxiRfsFf9C.jpg,1957-04-10,12 Angry Men,False,8.555,9794
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9415,False,/l2zqOzP0HVdH6Reor96b0nGlKxp.jpg,"[28, 12, 878]",9562,en,Timeline,A group of archaeological students become trap...,3.0360,/vexgfnhdlKERRMMdyVYLBXx89LW.jpg,2003-11-26,Timeline,False,5.729,1147
9416,False,/8nluZo04z9Y8iynYmnMmvO9bU9L.jpg,"[27, 9648]",10053,en,When a Stranger Calls,"Far away from the site of a gruesome murder, a...",2.2326,/r5FAdQAtgRpHuSI4x5ydvcVHuFz.jpg,2006-02-03,When a Stranger Calls,False,5.728,1133
9417,False,/lePVhFlkuRsE24agMApfg1V4wrB.jpg,"[35, 10749]",15681,it,Ex,"Six people struggling with their relationship,...",0.8957,/hQ5R1mZMaAT7wuyytBHxUeXuzZC.jpg,2009-02-06,Ex,False,5.700,464
9418,False,/ifOEPOHMnoT9YRu8dcvf26HsW47.jpg,"[35, 80, 28]",10723,en,Bulletproof,An undercover police officer named Rock Keats ...,4.2741,/iI7G9YXxodrqkQPKis1y3EKP8wJ.jpg,1996-09-06,Bulletproof,False,5.700,622
9419,False,/1MllG91Hzn5cgmN4uFn0Jg2D0i6.jpg,"[27, 9648]",9877,en,Urban Legend,A college campus is plagued by a vicious seria...,2.3443,/dUvZDNU9G0njhM628NA5phASntq.jpg,1998-09-25,Urban Legend,False,5.727,1431

In [18]:
df[["title", "overview"]]

,title,overview
0,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...
1,The Godfather,"Spanning the years 1945 to 1955, a chronicle o..."
2,The Godfather Part II,In the continuing saga of the Corleone crime f...
3,Schindler's List,The true story of how businessman Oskar Schind...
4,12 Angry Men,The defense and the prosecution have rested an...
...,...,...
9415,Timeline,A group of archaeological students become trap...
9416,When a Stranger Calls,"Far away from the site of a gruesome murder, a..."
9417,Ex,"Six people struggling with their relationship,..."
9418,Bulletproof,An undercover police officer named Rock Keats ...
9419,Urban Legend,A college campus is plagued by a vicious seria...

In [19]:
df["overview"].isnull().sum()

np.int64(2)

In [20]:
df.dropna(inplace=True)

In [21]:
from text_preprocessing_pipeline import preprocess_text

df["clean_overview"] = df["overview"].apply(preprocess_text)

In [22]:
df[["title", "overview", "clean_overview"]]

,title,overview,clean_overview
0,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,imprison 1940 doubl murder wife lover upstand ...
1,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",span year 1945 1955 chronicl fiction italianam...
2,The Godfather Part II,In the continuing saga of the Corleone crime f...,continu saga corleon crime famili young vito c...
3,Schindler's List,The true story of how businessman Oskar Schind...,true stori businessman oskar schindler save th...
4,12 Angry Men,The defense and the prosecution have rested an...,defens prosecut rest juri file juri room decid...
...,...,...,...
9415,Timeline,A group of archaeological students become trap...,group archaeolog student becom trap past go re...
9416,When a Stranger Calls,"Far away from the site of a gruesome murder, a...",far away site gruesom murder teenag name jill ...
9417,Ex,"Six people struggling with their relationship,...",six peopl struggl relationship lack thereof cr...
9418,Bulletproof,An undercover police officer named Rock Keats ...,undercov polic offic name rock keat befriend d...
9419,Urban Legend,A college campus is plagued by a vicious seria...,colleg campu plagu viciou serial killer murder...